CREATE TABLE kava (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nazev TEXT NOT NULL,
    typ TEXT NOT NULL,
    region_id INT,
    FOREIGN KEY (region_id) REFERENCES regiony(id)
);

INSERT INTO kava (nazev, typ, region_id) VALUES
('Ethiopia Yirgacheffe', 'Arabica', 1),
('Ethiopia Sidamo', 'Arabica', 1),
('Ethiopia Harrar', 'Arabica', 1),
('Colombia Huila', 'Arabica', 2),
('Colombia Supremo', 'Arabica', 2),
('Colombia Excelso', 'Arabica', 2),
('Brazil Cerrado', 'Arabica', 3),
('Brazil Santos', 'Arabica', 3),
('Brazil Fazenda Primavera', 'Arabica', 3),
('Kenya AA Nyeri', 'Arabica', 4),
('Kenya AB Muranga', 'Arabica', 4),
('Kenya Peaberry', 'Arabica', 4),
('Guatemala Antigua', 'Arabica', 5),
('Guatemala Huehuetenango', 'Arabica', 5),
('Guatemala Cobán', 'Arabica', 5),
('India Robusta Parchment', 'Robusta', 6),
('India Monsooned Malabar', 'Arabica', 6),
('India Cherry Robusta', 'Robusta', 6),
('Costa Rica Tarrazú Honey', 'Arabica', 7),
('Costa Rica SHB', 'Arabica', 7),
('Costa Rica La Pastora', 'Arabica', 7),
('El Salvador Pacamara', 'Arabica', 8),
('El Salvador Bourbon', 'Arabica', 8),
('El Salvador Santa Ana', 'Arabica', 8),
('Sumatra Mandheling', 'Arabica', 9),
('Sumatra Gayo', 'Arabica', 9),
('Java Estate', 'Arabica', 9),
('Nicaragua Segovia', 'Arabica', 10),
('Nicaragua Jinotega', 'Arabica', 10),
('Nicaragua Matagalpa', 'Arabica', 10),
('Peru Cajamarca', 'Arabica', 11),
('Peru Chanchamayo', 'Arabica', 11),
('Peru Amazonas', 'Arabica', 11),
('Rwanda Gikanda', 'Arabica', 12),
('Rwanda Kanzu', 'Arabica', 12),
('Rwanda Shyira', 'Arabica', 12),
('Blend 70/30', 'Mix', 13),
('Espresso House Blend', 'Mix', 13),
('Morning Coffee Blend', 'Mix', 13),
('Colombia Decaf Sugarcane', 'Arabica', 14),
('Colombia Decaf Swiss Water', 'Arabica', 14),
('Ethiopia Guji Natural', 'Arabica', 15),
('Ethiopia Guji Washed', 'Arabica', 15),
('Ethiopia Guji Anaerobic', 'Arabica', 15);